### ISSUE TITLE
Create a CRON Job

### ISSUE THREAD

**Issue by craigmcampbell** [craigmcampbell/learning-go#10]
**Objective**: Set up a CRON job to execute a simple Go task

**Tasks**:
- [ ] Create a small application that will post a message to Slack
- [ ] Set up a CRON job that will run the task
- [ ] Set to run every hour and monitor
